USE NHLDataWarehouse;
GO

IF OBJECT_ID('audit.LOAD_BATCH', 'U') IS NULL
BEGIN
    CREATE TABLE audit.LOAD_BATCH
    (
        LOAD_BATCH_ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT LOAD_BATCH_pk PRIMARY KEY,
        SOURCE_SYSTEM VARCHAR(50) NOT NULL,
        LOAD_START_DATE DATETIME2 NOT NULL CONSTRAINT LOAD_BATCH_LOAD_START_DATE_df DEFAULT (SYSUTCDATETIME()),
        LOAD_END_DATE DATETIME2 NULL,
        STATUS VARCHAR(20) NOT NULL,
        ROWS_INSERTED INT NULL,
        ROWS_UPDATED INT NULL,
        ERROR_MESSAGE NVARCHAR(MAX) NULL
    );
END
GO
