USE NHLDataWarehouse;
GO

IF OBJECT_ID('dimension.TEAM_DIM', 'U') IS NULL
BEGIN
    CREATE TABLE dimension.TEAM_DIM
    (
        TEAM_KEY INT IDENTITY(1,1) NOT NULL CONSTRAINT TEAM_DIM_pk PRIMARY KEY,
        TEAM_ID INT NOT NULL,
        TEAM_NAME VARCHAR(100) NOT NULL,
        TEAM_ABBREVIATION VARCHAR(10) NULL,
        CONFERENCE VARCHAR(50) NULL,
        DIVISION VARCHAR(50) NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT TEAM_DIM_IS_ACTIVE_df DEFAULT (1),
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT TEAM_DIM_CREATED_DATE_df DEFAULT (SYSUTCDATETIME()),
        MODIFIED_DATE DATETIME2 NULL,
        CONSTRAINT TEAM_DIM_TEAM_ID_uq UNIQUE (TEAM_ID)
    );
END
GO
