USE NHLDataWarehouse;
GO

IF OBJECT_ID('dimension.PLAYER_DIM', 'U') IS NULL
BEGIN
    CREATE TABLE dimension.PLAYER_DIM
    (
        PLAYER_KEY INT IDENTITY(1,1) NOT NULL CONSTRAINT PLAYER_DIM_pk PRIMARY KEY,
        PLAYER_ID INT NOT NULL,
        TEAM_KEY INT NULL,
        FIRST_NAME VARCHAR(100) NULL,
        LAST_NAME VARCHAR(100) NULL,
        FULL_NAME VARCHAR(200) NOT NULL,
        POSITION_CODE VARCHAR(10) NULL,
        SHOOTS_CATCHES VARCHAR(10) NULL,
        BIRTH_DATE DATE NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT PLAYER_DIM_IS_ACTIVE_df DEFAULT (1),
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT PLAYER_DIM_CREATED_DATE_df DEFAULT (SYSUTCDATETIME()),
        MODIFIED_DATE DATETIME2 NULL,
        CONSTRAINT PLAYER_DIM_PLAYER_ID_uq UNIQUE (PLAYER_ID),
        CONSTRAINT TEAM_DIM_PLAYER_DIM_fk FOREIGN KEY (TEAM_KEY) REFERENCES dimension.TEAM_DIM (TEAM_KEY)
    );
END
GO
