USE NHLDataWarehouse;
GO

IF OBJECT_ID('dimension.DATE_DIM', 'U') IS NULL
BEGIN
    CREATE TABLE dimension.DATE_DIM
    (
        DATE_KEY INT NOT NULL CONSTRAINT DATE_DIM_pk PRIMARY KEY,
        FULL_DATE DATE NOT NULL,
        CALENDAR_YEAR SMALLINT NOT NULL,
        CALENDAR_QUARTER TINYINT NOT NULL,
        CALENDAR_MONTH TINYINT NOT NULL,
        MONTH_NAME VARCHAR(20) NOT NULL,
        DAY_OF_MONTH TINYINT NOT NULL,
        DAY_OF_WEEK TINYINT NOT NULL,
        DAY_NAME VARCHAR(20) NOT NULL,
        IS_WEEKEND BIT NOT NULL,
        CONSTRAINT DATE_DIM_FULL_DATE_uq UNIQUE (FULL_DATE)
    );
END
GO
