USE NHLDataWarehouse;
GO

IF OBJECT_ID('fact.PLAYER_GAME_STATS_FACT', 'U') IS NULL
BEGIN
    CREATE TABLE fact.PLAYER_GAME_STATS_FACT
    (
        PLAYER_GAME_STATS_KEY BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_pk PRIMARY KEY,
        GAME_KEY BIGINT NOT NULL,
        PLAYER_KEY INT NOT NULL,
        TEAM_KEY INT NOT NULL,
        GOALS INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_GOALS_df DEFAULT (0),
        ASSISTS INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_ASSISTS_df DEFAULT (0),
        POINTS AS (GOALS + ASSISTS) PERSISTED,
        SHOTS INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_SHOTS_df DEFAULT (0),
        HITS INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_HITS_df DEFAULT (0),
        BLOCKS INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_BLOCKS_df DEFAULT (0),
        PENALTY_MINUTES INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_PENALTY_MINUTES_df DEFAULT (0),
        TIME_ON_ICE_SECONDS INT NULL,
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_CREATED_DATE_df DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PLAYER_GAME_STATS_FACT_GAME_KEY_PLAYER_KEY_uq UNIQUE (GAME_KEY, PLAYER_KEY),
        CONSTRAINT GAME_FACT_PLAYER_GAME_STATS_FACT_fk FOREIGN KEY (GAME_KEY) REFERENCES fact.GAME_FACT (GAME_KEY),
        CONSTRAINT PLAYER_DIM_PLAYER_GAME_STATS_FACT_fk FOREIGN KEY (PLAYER_KEY) REFERENCES dimension.PLAYER_DIM (PLAYER_KEY),
        CONSTRAINT TEAM_DIM_PLAYER_GAME_STATS_FACT_fk FOREIGN KEY (TEAM_KEY) REFERENCES dimension.TEAM_DIM (TEAM_KEY)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PLAYER_GAME_STATS_FACT__PLAYER_KEY' AND object_id = OBJECT_ID('fact.PLAYER_GAME_STATS_FACT'))
    CREATE NONCLUSTERED INDEX IX_PLAYER_GAME_STATS_FACT__PLAYER_KEY ON fact.PLAYER_GAME_STATS_FACT (PLAYER_KEY);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PLAYER_GAME_STATS_FACT__TEAM_KEY' AND object_id = OBJECT_ID('fact.PLAYER_GAME_STATS_FACT'))
    CREATE NONCLUSTERED INDEX IX_PLAYER_GAME_STATS_FACT__TEAM_KEY ON fact.PLAYER_GAME_STATS_FACT (TEAM_KEY);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PLAYER_GAME_STATS_FACT__GAME_KEY' AND object_id = OBJECT_ID('fact.PLAYER_GAME_STATS_FACT'))
    CREATE NONCLUSTERED INDEX IX_PLAYER_GAME_STATS_FACT__GAME_KEY ON fact.PLAYER_GAME_STATS_FACT (GAME_KEY);
GO
