USE NHLDataWarehouse;
GO

IF OBJECT_ID('fact.GAME_FACT', 'U') IS NULL
BEGIN
    CREATE TABLE fact.GAME_FACT
    (
        GameKey BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT GAME_FACT_pk PRIMARY KEY,
        GameID BIGINT NOT NULL,
        DateKey INT NOT NULL,
        Season VARCHAR(10) NULL,
        GameType VARCHAR(20) NULL,
        HomeTeamKey INT NOT NULL,
        AwayTeamKey INT NOT NULL,
        HomeGoals INT NULL,
        AwayGoals INT NULL,
        HomeShots INT NULL,
        AwayShots INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT GAME_FACT_CreatedDate_df DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT GAME_FACT_GameID_uq UNIQUE (GameID),
        CONSTRAINT DATE_DIM_GAME_FACT_fk FOREIGN KEY (DateKey) REFERENCES dimension.DATE_DIM (DateKey),
        CONSTRAINT TEAM_DIM_GAME_FACT_fk FOREIGN KEY (HomeTeamKey) REFERENCES dimension.TEAM_DIM (TeamKey),
        CONSTRAINT TEAM_DIM_GAME_FACT_fk2 FOREIGN KEY (AwayTeamKey) REFERENCES dimension.TEAM_DIM (TeamKey)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GAME_FACT__DATE_KEY' AND object_id = OBJECT_ID('fact.GAME_FACT'))
    CREATE NONCLUSTERED INDEX IX_GAME_FACT__DATE_KEY ON fact.GAME_FACT (DateKey);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GAME_FACT__HOME_TEAM_KEY' AND object_id = OBJECT_ID('fact.GAME_FACT'))
    CREATE NONCLUSTERED INDEX IX_GAME_FACT__HOME_TEAM_KEY ON fact.GAME_FACT (HomeTeamKey);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GAME_FACT__AWAY_TEAM_KEY' AND object_id = OBJECT_ID('fact.GAME_FACT'))
    CREATE NONCLUSTERED INDEX IX_GAME_FACT__AWAY_TEAM_KEY ON fact.GAME_FACT (AwayTeamKey);
GO
