USE NHLDataWarehouse;
GO

IF OBJECT_ID('fact.PLAYER_GAME_STATS_FACT', 'U') IS NULL
BEGIN
    CREATE TABLE fact.PLAYER_GAME_STATS_FACT
    (
        PlayerGameStatsKey BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_pk PRIMARY KEY,
        GameKey BIGINT NOT NULL,
        PlayerKey INT NOT NULL,
        TeamKey INT NOT NULL,
        Goals INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_Goals_df DEFAULT (0),
        Assists INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_Assists_df DEFAULT (0),
        Points AS (Goals + Assists) PERSISTED,
        Shots INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_Shots_df DEFAULT (0),
        Hits INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_Hits_df DEFAULT (0),
        Blocks INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_Blocks_df DEFAULT (0),
        PenaltyMinutes INT NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_PenaltyMinutes_df DEFAULT (0),
        TimeOnIceSeconds INT NULL,
        CreatedDate DATETIME2 NOT NULL CONSTRAINT PLAYER_GAME_STATS_FACT_CreatedDate_df DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PLAYER_GAME_STATS_FACT_GameKey_PlayerKey_uq UNIQUE (GameKey, PlayerKey),
        CONSTRAINT GAME_FACT_PLAYER_GAME_STATS_FACT_fk FOREIGN KEY (GameKey) REFERENCES fact.GAME_FACT (GameKey),
        CONSTRAINT PLAYER_DIM_PLAYER_GAME_STATS_FACT_fk FOREIGN KEY (PlayerKey) REFERENCES dimension.PLAYER_DIM (PlayerKey),
        CONSTRAINT TEAM_DIM_PLAYER_GAME_STATS_FACT_fk FOREIGN KEY (TeamKey) REFERENCES dimension.TEAM_DIM (TeamKey)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PLAYER_GAME_STATS_FACT__PLAYER_KEY' AND object_id = OBJECT_ID('fact.PLAYER_GAME_STATS_FACT'))
    CREATE NONCLUSTERED INDEX IX_PLAYER_GAME_STATS_FACT__PLAYER_KEY ON fact.PLAYER_GAME_STATS_FACT (PlayerKey);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PLAYER_GAME_STATS_FACT__TEAM_KEY' AND object_id = OBJECT_ID('fact.PLAYER_GAME_STATS_FACT'))
    CREATE NONCLUSTERED INDEX IX_PLAYER_GAME_STATS_FACT__TEAM_KEY ON fact.PLAYER_GAME_STATS_FACT (TeamKey);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PLAYER_GAME_STATS_FACT__GAME_KEY' AND object_id = OBJECT_ID('fact.PLAYER_GAME_STATS_FACT'))
    CREATE NONCLUSTERED INDEX IX_PLAYER_GAME_STATS_FACT__GAME_KEY ON fact.PLAYER_GAME_STATS_FACT (GameKey);
GO
