USE NHLDataWarehouse;
GO

IF OBJECT_ID('fact.GAME_FACT', 'U') IS NULL
BEGIN
    CREATE TABLE fact.GAME_FACT
    (
        GAME_KEY BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT GAME_FACT_pk PRIMARY KEY,
        GAME_ID BIGINT NOT NULL,
        DATE_KEY INT NOT NULL,
        SEASON VARCHAR(10) NULL,
        GAME_TYPE VARCHAR(20) NULL,
        HOME_TEAM_KEY INT NOT NULL,
        AWAY_TEAM_KEY INT NOT NULL,
        HOME_GOALS INT NULL,
        AWAY_GOALS INT NULL,
        HOME_SHOTS INT NULL,
        AWAY_SHOTS INT NULL,
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT GAME_FACT_CREATED_DATE_df DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT GAME_FACT_GAME_ID_uq UNIQUE (GAME_ID),
        CONSTRAINT DATE_DIM_GAME_FACT_fk FOREIGN KEY (DATE_KEY) REFERENCES dimension.DATE_DIM (DATE_KEY),
        CONSTRAINT TEAM_DIM_GAME_FACT_fk FOREIGN KEY (HOME_TEAM_KEY) REFERENCES dimension.TEAM_DIM (TEAM_KEY),
        CONSTRAINT TEAM_DIM_GAME_FACT_fk2 FOREIGN KEY (AWAY_TEAM_KEY) REFERENCES dimension.TEAM_DIM (TEAM_KEY)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GAME_FACT__DATE_KEY' AND object_id = OBJECT_ID('fact.GAME_FACT'))
    CREATE NONCLUSTERED INDEX IX_GAME_FACT__DATE_KEY ON fact.GAME_FACT (DATE_KEY);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GAME_FACT__HOME_TEAM_KEY' AND object_id = OBJECT_ID('fact.GAME_FACT'))
    CREATE NONCLUSTERED INDEX IX_GAME_FACT__HOME_TEAM_KEY ON fact.GAME_FACT (HOME_TEAM_KEY);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GAME_FACT__AWAY_TEAM_KEY' AND object_id = OBJECT_ID('fact.GAME_FACT'))
    CREATE NONCLUSTERED INDEX IX_GAME_FACT__AWAY_TEAM_KEY ON fact.GAME_FACT (AWAY_TEAM_KEY);
GO
