USE NHLDataWarehouse;
GO

IF OBJECT_ID('staging.PLAYER_GAME_STATS_RAW', 'U') IS NULL
BEGIN
    CREATE TABLE staging.PLAYER_GAME_STATS_RAW
    (
        RAW_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PLAYER_GAME_STATS_RAW_pk PRIMARY KEY,
        SOURCE_SYSTEM VARCHAR(50) NOT NULL CONSTRAINT PLAYER_GAME_STATS_RAW_SOURCE_SYSTEM_df DEFAULT ('NHL API'),
        LOAD_BATCH_ID UNIQUEIDENTIFIER NOT NULL,
        RAW_JSON NVARCHAR(MAX) NULL,
        GAME_ID BIGINT NULL,
        PLAYER_ID INT NULL,
        TEAM_ID INT NULL,
        GOALS INT NULL,
        ASSISTS INT NULL,
        SHOTS INT NULL,
        HITS INT NULL,
        BLOCKS INT NULL,
        PENALTY_MINUTES INT NULL,
        TIME_ON_ICE_SECONDS INT NULL,
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT PLAYER_GAME_STATS_RAW_CREATED_DATE_df DEFAULT (SYSUTCDATETIME())
    );
END
GO
