USE NHLDataWarehouse;
GO

IF OBJECT_ID('staging.TEAM_RAW', 'U') IS NULL
BEGIN
    CREATE TABLE staging.TEAM_RAW
    (
        RAW_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT TEAM_RAW_pk PRIMARY KEY,
        SOURCE_SYSTEM VARCHAR(50) NOT NULL CONSTRAINT TEAM_RAW_SOURCE_SYSTEM_df DEFAULT ('NHL API'),
        LOAD_BATCH_ID UNIQUEIDENTIFIER NOT NULL,
        RAW_JSON NVARCHAR(MAX) NULL,
        TEAM_ID INT NULL,
        TEAM_NAME VARCHAR(100) NULL,
        TEAM_ABBREVIATION VARCHAR(10) NULL,
        CONFERENCE VARCHAR(50) NULL,
        DIVISION VARCHAR(50) NULL,
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT TEAM_RAW_CREATED_DATE_df DEFAULT (SYSUTCDATETIME())
    );
END
GO
