USE NHLDataWarehouse;
GO

IF OBJECT_ID('staging.PLAYER_RAW', 'U') IS NULL
BEGIN
    CREATE TABLE staging.PLAYER_RAW
    (
        RAW_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PLAYER_RAW_pk PRIMARY KEY,
        SOURCE_SYSTEM VARCHAR(50) NOT NULL CONSTRAINT PLAYER_RAW_SOURCE_SYSTEM_df DEFAULT ('NHL API'),
        LOAD_BATCH_ID UNIQUEIDENTIFIER NOT NULL,
        RAW_JSON NVARCHAR(MAX) NULL,
        PLAYER_ID INT NULL,
        TEAM_ID INT NULL,
        FIRST_NAME VARCHAR(100) NULL,
        LAST_NAME VARCHAR(100) NULL,
        FULL_NAME VARCHAR(200) NULL,
        POSITION_CODE VARCHAR(10) NULL,
        SHOOTS_CATCHES VARCHAR(10) NULL,
        BIRTH_DATE DATE NULL,
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT PLAYER_RAW_CREATED_DATE_df DEFAULT (SYSUTCDATETIME())
    );
END
GO
