USE NHLDataWarehouse;
GO

IF OBJECT_ID('staging.GAME_RAW', 'U') IS NULL
BEGIN
    CREATE TABLE staging.GAME_RAW
    (
        RAW_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT GAME_RAW_pk PRIMARY KEY,
        SOURCE_SYSTEM VARCHAR(50) NOT NULL CONSTRAINT GAME_RAW_SOURCE_SYSTEM_df DEFAULT ('NHL API'),
        LOAD_BATCH_ID UNIQUEIDENTIFIER NOT NULL,
        RAW_JSON NVARCHAR(MAX) NULL,
        GAME_ID BIGINT NULL,
        GAME_DATE DATE NULL,
        SEASON VARCHAR(10) NULL,
        GAME_TYPE VARCHAR(20) NULL,
        HOME_TEAM_ID INT NULL,
        AWAY_TEAM_ID INT NULL,
        HOME_GOALS INT NULL,
        AWAY_GOALS INT NULL,
        HOME_SHOTS INT NULL,
        AWAY_SHOTS INT NULL,
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT GAME_RAW_CREATED_DATE_df DEFAULT (SYSUTCDATETIME())
    );
END
GO
